version: "3"
services:
  hub:
    image: selenium/hub:3.141.59-20210422
    ports:
      - "4444:4444"


  chrome:
    image: selenium/node-chrome:3.141.59-20210422
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    shm_size: '2gb'


  firefox:
    image: selenium/node-firefox:3.141.59-20210422
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    shm_size: '2gb'

  bdd:
    image: icemeetscoke/uiautomation
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
    volumes:
      -  C:\Users\diemol\Downloads\test-result:/usr/share/automation/target/html
